- app/build.gradle
- app/src/test/java/io/github/droidkaigi/confsched/dao/SessionDaoTest.java
This test makes mock instances for all dependencies including OrmaDatabase.
So shouldn't be affected by the changes of any dependencies.
> Adds a first unit test for SessionDao as a proof of concept.

- app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java
This fixes some crashes of "Can not perform this action after onSaveInstanceState" and also fixes the leak of MainActivity instance when regeneration of MainActivity such as changing the locale.
Perhaps this PR fixes #119.
> unsubscribe() when MainActivity is destroyed.

- app/build.gradle
- app/src/androidTest/java/io/github/droidkaigi/confsched/activity/SessionDetailActivityTest.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/SessionDetailActivity.java
- app/src/main/res/layout/fragment_session_detail.xml
- circle.yml
The tests verify initial views are correctly rendered and external Intents are
correctly thrown when clicking the Twitter/GitHub icons by launching the SessionDetailActivity
on connected emulators or devices.
Note that this is the first time for me to setup an emulator on CircleCI.
I referred to [this document](https://circleci.com/docs/android) on how to run an emulator on the CircleCI.
If the pre-submit fails, let me play around the setup until the pre-submit becomes green.
> Adds first UI tests for SessionDetailActivity using Espresso.

- app/src/main/res/drawable/tag_language.xml
If `<shape>` does not provide child `<solid>`, it's base color fallbacks to black pre API 17.
Here's screenshot of Xperia SX (SO-05D) (4.1.2).
> Fix base color of shape drawable is falling back to black on API 16

- app/src/androidTest/java/io/github/droidkaigi/confsched/activity/SessionDetailActivityTest.java
- circle.yml
Remove Espresso test temporary. Because UI test is heavy, CI test is not stable and take so long time.
> Remove espresso test temporary.

- app/src/main/res/values-ja/strings.xml
In Japanese string resources
Before:
`...会期中は、セッション（複数ルーム）以外にも以外にも協賛企業の各種出展があります...`
After:
`...会期中は、セッション（複数ルーム）以外にも協賛企業の各種出展があります...`
> Fixed a typo in string resources

- app/src/main/res/raw/sessions_en.json
Despite session_en.json, places and categories are written in Japanese.
I translated them into English.  
The same as strings displayed in current `Map`.
ルーム{A,B,C,D} => Hole {A,B,C,D}  
基調講演会場 => Keynote venue  
基調講演 => Keynote  
その他 => Others  
UI・デザイン => UI and Design  
ハードウェア => Hardware  
プラットフォーム => Platform  
開発環境・ツール => Environment and Tool  
メンテナンス => Maintenance  
Androidの最新動向 => Latest Trend in Android 
If terms are wrong, please tell me that. I will fix it.
> Translated Japanese words in session_en.json into English

- app/build.gradle
- app/src/main/res/layout/activity_web_view.xml
- app/src/main/res/layout/fragment_sessions.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings_urls.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/styles_about.xml
- app/src/main/res/values/styles_sponsor.xml
**edit**: this pr only includes lint-violation fixes. Enabling `abortOnError` is a next time issue.
---
Do not disable `lintOptions.abortOnError`, which can find critical errors.
This pull-request re-enable `abortOnError` and supress critical lint errors.
FYI: https://github.com/konifar/droidkaigi2016/pull/129 enables `./gradlew check` which includes `./gradlew lint`.
@konifar: you can reject this pull-request if you don't like this. It might cause a lot of CI failures :)
> fix lint violations

- app/build.gradle
Google map api key is diffrent from DEBUG build and RELEASE build.
> Fixed release map api key

- circle.yml
- deploy.sh
Removed debug build deploy to Deploygate, because `1.0.0` was already released.
> Remove debug build deploy

- app/src/main/java/io/github/droidkaigi/confsched/activity/WebViewActivity.java
Thank you for amazing app!!
Now, WebViewActivity is not enabled JavaScript. And WebViewActivity can link move.
So WebViewActivity displays a page not completely.
If you enabled JavaScript, WebViewActivity contains the vulnerability.
I wrote code that displays the chrome custom tab at the link click of WebViewActivity.
> Displays the chrome custom tab at the link click of WebViewActivity

- app/src/main/java/io/github/droidkaigi/confsched/di/AppModule.java
Modify tinily to keep injection provider method name consistent.
Renamed from `provides...` to `provide...` as GoogleAanalyticsTracker is the only provider method that has `provides` prefix.
> Modify method prefix from "provides" to "provide"

- app/src/main/res/layout/fragment_sessions.xml
I fixed unfocused tabs text color along the material design guideline ( https://www.google.com/design/spec/components/tabs.html ).
> Unfocused tab color: #fff 70%
> change unfocused tab color

- app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java
Use `centerInside()` for non-square speaker images.
Before | After
------------ | -------------
> Fix distorted speaker image.

- app/src/main/res/drawable/rect_edit_text_cursor.xml
- app/src/main/res/values/styles.xml
Since the drawable rather than color resource has been specified, the input cursor of EditText did not appear.
> fix edit text cursor

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched/util/PrefUtil.java
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
This PR is for #168 .
User can choose whether to receive notifications.
> notification setting

- app/src/main/res/layout/fragment_about.xml
Closes: #208 
I was going to modify the margin of @style/AboutTitle from 8dp to 16dp, but it was applied to the TextView with text value 'DroidKaigiについて' as well so I decided not to do so. Instead, I added margin bottom 8dp to have 16dp in total.
Below is the screen shot:
> Add 16dp space in total between about_social and the border above it

- app/src/main/res/layout/fragment_session_detail.xml
I was going to modify the description text is selectable in session detail page.
However, text selectable is different look each os versions. 
How do you think?
Below is the screen shot:
Android 6
Android 5
If you want to change select color or some selectable styles, please let me know.
> Modified session detail description text is selectable

- app/src/main/res/layout/fragment_session_detail.xml
This is a bug from https://github.com/konifar/droidkaigi2016/pull/215.
When the user open SessionDetail page, the top area including tags and speaker is shown in the back of header.
> Fixed detail page first visible position

- app/src/main/AndroidManifest.xml
SecurityException occurs when this app notifies sessions on JB.
Add VIBRATE permission as a workaround.
FYR http://stackoverflow.com/questions/13602190/java-lang-securityexception-requires-vibrate-permission-on-jelly-bean-4-2
stacktrace on emulator(Galaxy Nexus API 16)
```
java.lang.RuntimeException: Unable to start receiver io.github.droidkaigi.confsched.receiver.SessionScheduleReceiver: java.lang.SecurityException: Requires VIBRATE permission
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2236)
at android.app.ActivityThread.access$1500(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at …
```
> Add VIBRATE permission for old JB devices.

- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched/util/PrefUtil.java
- app/src/main/java/io/github/droidkaigi/confsched/widget/SettingSwitchRowView.java
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
Support below notification features:
- Add `category` for Priority-only mode
- Heads-up notification
- Disable Heads-up notification on settings.
- Show on Lock-screen
----
Priority-only mode is available on Lollipop and above.
Android system filters interruption(Notification's sound and vibration) referring to the `category` in Priority mode.
So our app should set `category` to notifications.
https://developer.android.com/design/patterns/notifications.html#set_a_notification_category
----
Heads-up notification interrupts user's attention.
Even if users focus other, Users can notice favorite sessions.
However, Heads-up notification is noisy.
So we add a setting to disable Heads-up notification.
This setting is hidden on Android 4.4 and below, because Heads-up notification is available on …
> Support Lollipop notification feature

- app/src/main/java/io/github/droidkaigi/confsched/widget/CustomLikeButton.java
- app/src/main/res/layout/item_session.xml
This issue’s cause is intercepted TouchEvent by RecyclerView.
(It occur not only LikeButton case.)
I implemented if LikeButton touched, parent not intercepted TouchEvent.
But develop a side effect.
When touch LikeButton and drag, not scroll parent RecyclerView.
If does not want this behavior, please reject PR.
> Implemented  #206 - Favorite button doesn't return original scale

- app/src/main/java/io/github/droidkaigi/confsched/widget/SettingSwitchRowView.java
Added `setOnCheckedChangeListener` replaces necessary listener with new one.
This problem makes wrong behavior for SettingSwitchRowView.
This PR resolves the problem above.
Sorry. I made this problem at 1248e6aeef5c712b0d2de42e49c6cad253d8d077 in #228.
> Do not replace Switch's `onCheckedChangeListener` in SettingSwitchRowView

- app/src/main/res/layout/fragment_about.xml
Closes: #237 
I've added circular ripple effect to social icons on about page referencing `view_speaker_sns_icons.xml`.
I've realized that in `view_speaker_sns_icons.xml`, `RelativeLayout` is used for achieving the ripple effects, which is great, but I thought `FrameLayout` can be used in this case as no `RelativeLayout` attribute is used in the child views. Since `FrameLayout` is less costly than `RelativeLayout` in terms of performance (in my understanding..), I've decided to use `FrameLayout` in my pull request.
If replacing `RelativeLayout` with `FrameLayout` for `view_speaker_sns_icons.xml` is considered as appropriate, I'd like to add that replacement in this PR as well. 
What do you think? 
Corresponding code: https://github.com/konifar/droidkaigi2016/blob/2e382c6b9f1dfe95867b0d5ab6 …
> Added circular ripple effect to social icons on about page

- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
@yulily100 created notification icon. https://github.com/konifar/droidkaigi2016/pull/250
So I changed it.
> Changed notification icon

- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
IMO, heads-up `enable` state depends on notification setting but it's `checked` state should be independent.
> Proposal: HeadsUp setting should not be changed by notification setting

- app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java
Closes: #239 
I've modified not to show loading view on fetch and save data. While loading data, the loading view still shows and it will dismiss when loading is finished.
> Modified not to show loading view on fetch and save data

- app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java
Response from GitHub API is paginated to 30 items by default. I increased it to 100 (this is maximum)
[GitHub API v3 | GitHub Developer Guide](https://developer.github.com/v3/#pagination)
**Before**
**After**
> Increase maximum number of contributors can be displayed from 30 to 100.

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java
`NOTIFICATION_PREFERENCES` intent category provides a way to configure settings quickly.
Users move to settings screen from settings icon in revealed notification in Lollipop and above.
Long tap reveals a notification to show icons.
> Support `NOTIFICATION_PREFERENCES` intent category.

- app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java
Orientation change causes broken layout and string.
Special thanks to @ichigotake ..!!!
> Fix in-app locale being reset on orientation change

- app/build.gradle
- build.gradle
* Use android-retrolambda-lombok.
* our company has achievement in production.
* `abortOnError false` removed, because 'Error' rules may terminate the app.
> abortOnError true

- app/src/main/java/io/github/droidkaigi/confsched/model/Session.java
- app/src/main/res/layout/fragment_session_detail.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-ja/strings.xml
- app/src/main/res/values/strings.xml
Thanks to @jmatsu. https://github.com/konifar/droidkaigi2016/pull/308
Added slide url link if it exists.
slide section is not shown if it does not exist.
> Added slide url to detail page

- app/build.gradle
Fixed at Orma v2.0.6, which includes https://github.com/gfx/Android-Orma/pull/193
Please :sob:
> Fix #318, crashes in Orma migration engines

- app/src/main/java/io/github/droidkaigi/confsched/MainApplication.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/BaseActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/ContributorsActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/SearchActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/SearchedSessionsActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/SessionDetailActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/SessionFeedbackActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/activity/WebViewActivity.java
- app/src/main/java/io/github/droidkaigi/confsched/di/AppModule.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/AboutFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/BaseFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/MapFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionDetailFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SponsorsFragment.java
The activity has to retain the reference of its component.
If you instantiate ActivityModule every time on the call of MainApplication::getComponent(), the scope will be broken; each child fragment has activity-scoped instances **separately** despite their life cycle should be tied to their activity.
Actually the custom scopes are not needed in this app and that's why there are no bugs related to them. So this PR is some kind of a reference.
> Use custom scopes appropriately

- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
Set accent color to notification icon(small icon) to get user's attention.
This feature is available on Lollipop and above.
----
> Set accent color to notifications.

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/prefs/DefaultPrefsSchema.java
- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched/util/LocaleUtil.java
I updated kvs-schema version. This diff is
* Generate initialize method in compile time
* Enable to specify builder class
This change makes schema class simple :smile: 
```java
@Table(name = "io.github.droidkaigi.confsched_preferences")
public abstract class DefaultPrefsSchema {
@Key("current_language_id")
String languageId;
@Key("notification_setting")
boolean notificationFlag;
@Key("heads_up_setting")
boolean headsUpFlag;
@Key("show_local_time")
boolean showLocalTimeFlag;
}
```
Previously, we need to write singleton code manually. To reduce boilerplate code, I updated the library to generate initialize method.
```
@Table(name = "io.github.droidkaigi.confsched_preferences")
public abstract class DefaultPrefsSchema {
...
-
-    private static DefaultPrefs prefs;
-
-    public static …
```
> Update kvs-schema version to 3.0.0

- app/src/androidTest/java/io/github/droidkaigi/confsched/util/AppUtilTest.java
- app/src/androidTest/java/io/github/droidkaigi/confsched/util/LocaleUtilTest.java
- app/src/androidTest/java/io/github/droidkaigi/confsched/util/LocaleUtilsTest.java
Do you the unit test has been successful?
I got this error.
```
LocaleUtilsTest.java
Error:(26, 27) エラー: シンボルを見つけられません
シンボル:   メソッド get(Context)
場所: クラス DefaultPrefsSchema
Error:(30, 27) エラー: シンボルを見つけられません
シンボル:   メソッド get(Context)
場所: クラス DefaultPrefsSchema
エラー2個
:app:compileRetrolambdaDevelopDebugAndroidTest
Error:Execution failed for task ':app:compileDevelopDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
```
I presume you forgot to rename the test class of kvs-schema at the time of [this commit](https://github.com/konifar/droidkaigi2016/commit/5f1b44806b1dc68c3dcbbd6b4a76d26fe994235d).
And it seems to have also forgotten to rename these test files name at the time of [this …
> Fix test class names

- app/src/main/res/raw/sessions_ar.json
- app/src/main/res/raw/sessions_en.json
- app/src/main/res/raw/sessions_ja.json
- app/src/main/res/raw/sessions_ko.json
Related Issue: https://github.com/konifar/droidkaigi2016/issues/334
I added 3 new movie urls: https://github.com/konifar/droidkaigi2016/issues/334#issuecomment-197222077 (finally 🙇 )
> Add 3 new movie urls

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/prefs/DefaultPrefsSchema.java
- app/src/main/java/io/github/droidkaigi/confsched/receiver/SessionScheduleReceiver.java
- app/src/main/java/io/github/droidkaigi/confsched/util/LocaleUtil.java
I updated KVS schema from `3.0.0` to `5.0.0`.
Some features were introduced in this update. A change that affects to this project is [Support default value](https://github.com/rejasupotaro/kvs-schema/pull/18). If a field is difined as a constant, KVS schema reads and assigns the value to the generated class as a default value like below.
```java
// Schema class
@Table(name = "io.github.droidkaigi.confsched_preferences")
public abstract class DefaultPrefsSchema {
@Key(name = "notification_setting")
final boolean notificationFlag = true;
```
```java
// Generated class
public boolean getNotificationFlag() {
return getBoolean("notification_setting", true); // A constant value we set is specified.
}
```
So we don't have to specify default values expressly.
```java
prefs.getNotificationFlag(); …
```
> Update KVS Schema and utilize a new feature

- app/build.gradle
- build.gradle
- I have added [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin). This allows all contributors to easily check whether the libraries this app depend on are all up-to-date :)
- Remove short `apk size` comment (If anybody does not like this modification I can revert this 🙇 )
Maybe in the near future we can integrate it to Circle CI and run the command and check the library updates regularly.
http://www.slideshare.net/shinobuokano7/gradle-pluginci-62464447/19?src=clipshare
Also, here is the result when I ran the command 
```
./gradlew delendencyUpdates
```
```
The following dependencies exceed the version found at the milestone revision level:
- com.android.databinding:adapters [1.1 <- 1.0-rc3]
- com.android.databinding:library [1.1 <- 1.0-rc3]
The following …
```
> Add gradle-versions-plugin

- app/build.gradle
See the issue https://github.com/jd-alexander/LikeButton/issues/19 cause of the problem that was fixed in v0.2.0.
> Fixed the app crashes on Pre-Lollipop devices.

- app/build.gradle
In this PR I have updated two libraries: RxJava and RxAndroid.
- [RxJava from 1.1.5 to 1.1.7](https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#version-117---july-10-2016-maven)
- [RxAndroid from 1.2.0 to 1.2.1](https://github.com/ReactiveX/RxAndroid/blob/master/CHANGES.md#version-121---june-16th-2016)
I have manually tested by myself by installing the app with `developDebug` and it seems ok, but just in case I would like other developers to check to make sure that this PR does not break anything. 🙇
> Update RxJava 1.1.5->1.1.7, RxAndroid 1.2.0->1.2.1

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched/fragment/SponsorsFragment.java
- app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java
- app/src/main/res/layout/fragment_session_detail.xml
- app/src/main/res/layout/fragment_sponsors.xml
- app/src/main/res/layout/item_session.xml
- app/src/main/res/values/styles_sponsor.xml
https://github.com/konifar/droidkaigi2016/issues/404
We use flow-layout on category tag view.
Now, we can use really awesome library called [flexbox-layout](https://github.com/google/flexbox-layout).
It's really awesome! Thanks @thagikura ! 👏
> Migrate to flexbox-layout from flowlayout

- app/src/main/res/raw/sessions_ar.json
- app/src/main/res/raw/sessions_en.json
- app/src/main/res/raw/sessions_ja.json
- app/src/main/res/raw/sessions_ko.json
close #309 
I happened to find the session slide url! 👍 
https://speakerdeck.com/masaki_mori/view-into-the-abyss
Also, I have found out that the movie url was missing on one of the sessions json files (I am sorry that was my mistake from old PR.. 🙇 ), so I modified to add the movie url in this PR as well.
> Add session slide url

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched/widget/MapSearchView.java
I have updated CircularReveal library from 1.3.1 to 2.0.1.
Changelogs can be found at Releases: https://github.com/ozodrukh/CircularReveal/releases
Below is GIFs showing the diff from UI perspective.
| 1.3.1 | 2.0.1|
|:---:|:---:|
|![1-3-1](https://cloud.githubusercontent.com/assets/920911/18783717/688b60a6-81c8-11e6-84e6-a36d0841ca74.gif)|![2-0-1](https://cloud.githubusercontent.com/assets/920911/18783719/6b03eae2-81c8-11e6-9906-ddc74907af77.gif)|
> Update CircularReveal 1.3.1 -> 2.0.1

- app/src/main/AndroidManifest.xml
I added `users-feature` to AndroidManifest.xml.
```xml
<uses-feature android:name="android.hardware.location.gps" />
```
According to the developer page, we must explicitly declare that `users-feature` if we uses the `ACCESS_FINE_LOCATION`.
https://developer.android.com/guide/topics/manifest/uses-feature-element.html
> Caution: If your app targets Android 5.0 (API level 21) or higher and uses the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission in order to receive location updates from the network or a GPS, respectively, you must also explicitly declare that your app uses the android.hardware.location.network or android.hardware.location.gps hardware features.
@hkurokawa announced it on Slack. Thanks!
https://droidkaigi.slack.com/archives/officialapp/p1475140680000159
> Added gps users-feature

- app/build.gradle
- app/src/main/java/io/github/droidkaigi/confsched/dao/ContributorDao.java
- app/src/main/java/io/github/droidkaigi/confsched/dao/SessionDao.java
- app/src/main/java/io/github/droidkaigi/confsched/di/AppModule.java
Upgrade Orma with newly-designed internal schemas (see [my post](http://gfx.hatenablog.com/entry/2016/10/10/190804)).
I have also fixed transactions because v3 has removed deprecated `transactionAsync()` methods.
ref. [diff v2.3.2...v3.0.0-rc2](https://github.com/gfx/Android-Orma/compare/v2.3.1...v3.0.0-rc2)
> Upgrade Orma to v3.0.0-rc2

- app/build.gradle
- build.gradle
ref: https://bitbucket.org/hvisser/android-apt/wiki/Migration
- Update gradle plugin to 2.2.1.
- And also remove android-apt plugin since android gradle plugin started annotation processing support natively from 2.2.
- See https://bitbucket.org/hvisser/android-apt/wiki/Migration
> Remove android-apt plugin

- app/build.gradle
ref: https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.2.1
This change will reduce lint warning.
> Update PermissionsDispatcher to 2.2.1.
