konifar/droidkaigi2016

app/app.iml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/droidkaigi/confsched/MainApplication.java, app/src/main/res/drawable-v21/clickable.xml, app/src/main/res/drawable-v21/clickable_white.xml, app/src/main/res/drawable/clickable.xml, app/src/main/res/drawable/clickable_white.xml, app/src/main/res/values/themes.xml, build.gradle
https://github.com/konifar/droidkaigi2016/issues/23
https://github.com/konifar/droidkaigi2016/issues/25
=> Fixed menu ripple and add crashlytics

.gitignore, app/fabric.properties, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Category.java, app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java, app/src/main/java/io/github/droidkaigi/confsched/widget/CategoryView.java, app/src/main/res/layout/fragment_session_detail.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
https://github.com/konifar/droidkaigi2016/issues/41
https://github.com/konifar/droidkaigi2016/issues/40
=> Improve detail page

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java, app/src/main/res/layout/activity_main.xml
https://github.com/konifar/droidkaigi2016/issues/44
https://github.com/konifar/droidkaigi2016/issues/45
=> Fixed drawer first select

circle.yml, deploy.sh
Add deploy section to circle ci.
=> Upload to deploygate

app/src/main/java/io/github/droidkaigi/confsched/model/Sponsor.java
This PR is corresponding to issue #20
=> Add sponsors

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java
Fixed https://github.com/konifar/droidkaigi2016/issues/62
=> Bug fix: No session shown after clean installation

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/MainContentStateBroker.java, app/src/main/java/io/github/droidkaigi/confsched/model/MainContentStateBrokerProvider.java, app/src/main/java/io/github/droidkaigi/confsched/model/Page.java, app/src/main/res/layout/fragment_sessions.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
=> Show empty view when no items in the list

app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/res/layout/fragment_sessions.xml, app/src/main/res/layout/fragment_sessions_tab.xml, app/src/main/res/layout/item_session.xml, app/src/main/res/raw/sessions_ja.json
* Removed SwipeRefreshView.
* Added sessions json data.
* Fixed session item layout.
=> Remove swipe refresh

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/AppUtil.java, app/src/main/java/io/github/droidkaigi/confsched/util/DateUtil.java
Fixed: https://github.com/konifar/droidkaigi2016/issues/49
=> Fixed locale

app/src/main/AndroidManifest.xml, app/src/main/java/io/github/droidkaigi/confsched/activity/SearchActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/SearchedSessionsActivity.java, app/src/main/java/io/github/droidkaigi/confsched/dao/CategoryDao.java, app/src/main/java/io/github/droidkaigi/confsched/dao/PlaceDao.java, app/src/main/java/io/github/droidkaigi/confsched/dao/SessionDao.java, app/src/main/java/io/github/droidkaigi/confsched/di/ActivityComponent.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SearchedSessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsByPlaceFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Category.java, app/src/main/java/io/github/droidkaigi/confsched/model/Place.java, app/src/main/java/io/github/droidkaigi/confsched/model/SearchGroup.java, app/src/main/java/io/github/droidkaigi/confsched/model/SearchResult.java, app/src/main/java/io/github/droidkaigi/confsched/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched/widget/SearchPlacesAndCategoriesView.java, app/src/main/java/io/github/droidkaigi/confsched/widget/SearchToolbar.java, app/src/main/res/anim/activity_fade_enter.xml, app/src/main/res/anim/activity_fade_exit.xml, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/activity_searched_sessions.xml, app/src/main/res/layout/item_search_category.xml, app/src/main/res/layout/item_search_place.xml, app/src/main/res/layout/item_search_result.xml, app/src/main/res/layout/item_search_title.xml, app/src/main/res/layout/toolbar_search.xml, app/src/main/res/layout/view_search_places_and_categories.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
Add place and category search. https://github.com/konifar/droidkaigi2016/issues/51
=> Improve search page

app/proguard-rules.pro, app/src/main/java/io/github/droidkaigi/confsched/widget/CategoryView.java, app/src/release/java/io/github/droidkaigi/StethoWrapper.java
https://github.com/konifar/droidkaigi2016/issues/24
Apk size is reduced from 4.3MB to 3.0MB.
=> Added proguard rules

app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/IntentUtil.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_urls.xml
Just add bug report link to the github.
=> Add bug report link.

app/src/main/java/io/github/droidkaigi/confsched/model/Sponsor.java
=> Add the link of yahoo japan.

app/src/main/res/layout/fragment_sponsors.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
and fixing TYPO (pratinum to platinum)
=> apply wording same as web page in sponsors list

app/src/main/res/raw/sessions_ja.json
fixed https://github.com/konifar/droidkaigi2016/issues/99
=> quick fix : set language id for issue #99

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/SearchActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/SearchedSessionsActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/SessionDetailActivity.java, app/src/main/java/io/github/droidkaigi/confsched/di/FragmentComponent.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SponsorsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/AnalyticsTracker.java
=> trac tap events in sponsors list

app/src/main/assets/license.html
#84 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/konifar/droidkaigi2016/104)
=> Fix Orma License

README.md
This pull request corresponds to #105 
Everything on README has already looked great but I tied to improve it even for a tiny bit.
I've tried to avoid any change that may cause unintended contextual modification but if anything seems weird, wrong, or irrelevant, feel free to add some comment or make revision right away! :dancer:
=> Update README.md for a tiny bit

app/src/main/res/layout/fragment_sponsors.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
issue #33
I suggest english alternative expressions which might improve strings.xml slightly.
You can see references put in commit messages.
=> English alternative expressions

app/src/main/res/values/themes.xml
this PR is for #103 .
Using @color/theme500 is okay?
=> set textColorLink

README.md
This pull request corresponds to issue #105 and pull request #106 , which I should have included this modification as well; I'm sorry about that.. :disappointed:
=> Update README.md for one more tiny improvement

gradle/wrapper/gradle-wrapper.properties
* Improve build performance
* measurement with 3 times
```
$ git checkout feature_update_gradle_version
$ ./gradlew clean
$ time ./gradlew assembleDebug
Total time: 2 mins 56.459 secs
Total time: 2 mins 55.672 secs
Total time: 2 mins 51.675 secs
```
```
$ git checkout master
$ ./gradlew clean
$ time ./gradlew assembleDebug
Total time: 2 mins 55.14 secs
Total time: 2 mins 57.621 secs
Total time: 2 mins 57.106 secs
```
=> Update gradle version to 2.11

app/build.gradle, app/src/main/java/io/github/droidkaigi/confsched/dao/SessionDao.java, app/src/main/java/io/github/droidkaigi/confsched/model/Session.java
* Upgrade Orma to v1.2.2, which includes a lot of bug fixes
* `Observable(selector.toList())` is useless. Use `selector.executeAsObservable()` instead.
* `selector.get(0)` is equivalent to `selector.value()`.
* Don't query non-indexed columns (`where("checked = ?", true)`). `@Column(indexed = true)` makes a query helper `checkedEq()`.
=> refactor use of Orma

app/src/main/res/values/dimens.xml
=> Fixed dimens

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
I was working on #80 and noticed #121 didn't remove `app_close_confirm` from strings.xml
=> Remove R.string.app_close_confirm since it is no longer used.

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/SearchedSessionsActivity.java, app/src/main/java/io/github/droidkaigi/confsched/activity/WebViewActivity.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/AppUtil.java
Set task description to the overview screen.
I used GooglePlay as reference.
* http://developer.android.com/intl/ja/reference/android/app/Activity.html#setTaskDescription(android.app.ActivityManager.TaskDescription)
* http://qiita.com/pside/items/e28dfdd1f42f7a2cb9f2
=> Set task description to the overview screen

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java
Just a tiny little bit customize.
=> Modify to cache get item count.

app/src/main/java/io/github/droidkaigi/confsched/MainApplication.java
Removed build config condition, because current Deploygate apk is development version.
=> Removed build config condition

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java
=> Deleted unused import and tag.

app/build.gradle, app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java
Just update some dependencies to the newest version.
=> Update gson, okhttp, retrofit.

app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
Keep the description up-to-date with the official website update.
see also https://github.com/konifar/droidkaigi2016/issues/33
=> Update DroidKaigi description

app/src/main/java/io/github/droidkaigi/confsched/util/AppUtil.java
You can get the version name more simply with this way.
=> Fix way to get the version name.

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
#133 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/konifar/droidkaigi2016/153)
=> Fix crash when no network

app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
=> Show language names in each language and apply immediately

deploy.sh
This PR enables testers to easily access the source code of installed app.
=> add github link of source tree to deploygate message

app/src/main/res/raw/sessions_en.json
With #29 .
For consistency, this change uses the names which are already used in the web page.
PR #146 was wrong, sorry. :bow: :bow:
=> Modified some categories' name in session_en.json

app/build.gradle
Just for incrementing the patch version number.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/konifar/droidkaigi2016/173)
=> Increment the version number

app/build.gradle, app/src/androidTest/java/io/github/droidkaigi/confsched/util/AppUtilsTest.java, app/src/debug/res/values/strings_no_trans.xml, app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java, app/src/main/res/values/strings_no_trans.xml, circle.yml
- if to switch. 
- It is easy to add languages.
https://github.com/google/gson/blob/master/CHANGELOG.md
https://github.com/square/okhttp/blob/master/CHANGELOG.md
https://github.com/JakeWharton/ThreeTenABP/blob/master/CHANGELOG.md
https://github.com/facebook/stetho/blob/master/CHANGELOG.md
=> Refactoring and Update dependencies

app/src/main/java/io/github/droidkaigi/confsched/activity/SearchedSessionsActivity.java
Deleted unused import statement :)
=> Delete unused import

app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/AppUtil.java, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
I removed some language label string in PR #154 but they are used in tags attached to the sessions.
I restored the language label strings for each languages.
=> Fix language tag.

app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java
=> fix window leak introduced in PR #154

app/src/main/res/layout/activity_session_feedback.xml, app/src/main/res/values/styles_feedback.xml
Fixed #158 .
- Add card style for each question item.
- Make title style bold.
=> Improve session feedback design

app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/util/IntentUtil.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/strings_urls.xml
=> Delete bug report link.

app/src/main/res/color/nav_view_colors.xml, app/src/main/res/layout/activity_main.xml
Simple solution for issue #193 .
=> Refine selected text color of navigation drawer

app/src/main/res/layout/activity_session_feedback.xml
Please check my PR :smiley_cat:
=> Remove inputType and enable line break of EditText

app/src/main/java/io/github/droidkaigi/confsched/fragment/AboutFragment.java, app/src/main/res/layout/fragment_about.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
Issue: https://github.com/konifar/droidkaigi2016/issues/200
=> Add the repository link to About page.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/io/github/droidkaigi/confsched/activity/ContributorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java, app/src/main/java/io/github/droidkaigi/confsched/dao/ContributorDao.java, app/src/main/java/io/github/droidkaigi/confsched/di/ActivityComponent.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/AboutFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Contributor.java, app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java, app/src/main/java/io/github/droidkaigi/confsched/widget/itemdecoration/DividerItemDecoration.java, app/src/main/res/drawable/border_small.xml, app/src/main/res/layout/activity_contributors.xml, app/src/main/res/layout/fragment_about.xml, app/src/main/res/layout/item_contributor.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
https://github.com/konifar/droidkaigi2016/issues/169
Add **ContributorsActivity** .
( This is arabian language )
Go to github user page.
Add **Contributor** table.
Column
- avatar_url
- github user profile image url.
- html_url 
- github user page. ( Like a https://github.com/gotokatsuya
- contributions 
- commit number.
- name
- github user name. **Primary Key**. This is not duplicated because github login name. 
Sorry, I could not translate "Contributors" into Arabian.
I try to use the GoogleTranslator.
```
<string name="about_contributors">مساهم</string>
```
=> Add contributors page

app/src/main/java/io/github/droidkaigi/confsched/activity/ContributorsActivity.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/AboutFragment.java, app/src/main/res/layout/activity_contributors.xml, app/src/main/res/layout/fragment_about.xml, app/src/main/res/layout/item_contributor.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
* Added tap effect.
* Added number of contributors to title.
* Fixed GitHubAPI error handling.
* Change list order in about page.
=> Improve contributors page

app/src/main/java/io/github/droidkaigi/confsched/activity/ContributorsActivity.java
ProgressBar is not gone when error occurs.
I forgot to handle. Sorry... :sob:
=> Fix progress should be gone when error

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java
Closes: #205 
I was going to implement the above issue's feature.
That is my first time to use `DataBinding` and some other libraries. 
So If you have some advices, please let me know.
Below is the screen shot:
=> Implemented #205 - Auto scroll up to top in sessions list page

app/src/main/res/drawable/ic_search_white_24dp_auto_mirrored.xml, app/src/main/res/drawable/img_default_cover_auto_mirrored.xml, app/src/main/res/layout/fragment_session_detail.xml, app/src/main/res/layout/nav_header.xml, app/src/main/res/menu/menu_sessions.xml, app/src/main/res/values/styles.xml
If user set Arabic language, search icon and default cover is mirrored.
=> RTL Drawable mirror

app/src/main/res/layout/fragment_session_detail.xml
Closes: #196 
I was going to add ripple effect in session detail page toolbar in above issue.
Please check this PR.
Below is the screen shot:
=> Modified #196 - Add ripple in session detail page toolbar

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched/util/AlarmUtil.java, app/src/main/java/io/github/droidkaigi/confsched/util/DataBindingAttributeUtil.java, app/src/main/java/io/github/droidkaigi/confsched/widget/SettingSwitchRowView.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/item_session.xml, app/src/main/res/layout/view_setting_switch_row.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/strings.xml
It is just for my internationalization session.
If the user is in Singapore, the first session start 11:00 (1 hours later)
The user can set from Setting page.
=> Add setting to show local time

app/src/main/res/values/themes.xml
ref. https://github.com/konifar/droidkaigi2016/issues/202
=> Set default button color as primary color of the app

app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/res/layout/fragment_sessions.xml
ref. https://github.com/konifar/droidkaigi2016/issues/199
=> Loading progress bar on sessions list

app/src/main/res/values-ja/strings_urls.xml, app/src/main/res/values/strings_urls.xml
=> Add english ver url.

app/src/main/java/io/github/droidkaigi/confsched/widget/SettingSwitchRowView.java
=> Fix typo `newValule`

app/src/main/res/values-ar/strings.xml
Translated to Arabic by using GoogleTranslate. #254
=> Translate Session's feedback page to Arabic.

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Page.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/colors.xml
=> #35 Change toolbar color in my schedule page.

app/src/main/res/layout/fragment_settings.xml
Corresponding issue: #245 
I've simply specified textSize to `@dimen/text_large` here.
=> Enlarge notification text

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java
=> #238 Fixed issue that toolbar shadow doesn't switch.

app/src/main/res/layout/fragment_session_detail.xml
=> Fix tag's margin in case of Arabic.

app/src/main/res/layout/view_setting_switch_row.xml
=> Use SwitchCompat

app/src/main/res/layout/fragment_settings.xml
I've noticed part of SettingsFragment is hidden on landscape orientation, so let's make it scrollable.
=> Make settings fragment scrollable

app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleSessionsTabFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java, app/src/main/res/drawable/tag_conflict.xml, app/src/main/res/layout/item_session.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values/strings.xml
Implemented #101 
Changes:
+ Add a conflict tag on a CardView
+ Add some resources for conflict tags
+ Refresh contents of RecyclerView when the statuses of sessions are changed
=> Added markers show conflicts of the sessions in My Schedule.

app/build.gradle
Read more about it here: https://bitbucket.org/hvisser/android-apt/issues/15
=> Use fully qualified plugin id for android-apt

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java
https://github.com/konifar/droidkaigi2016/issues/264
=> Modify not to refresh when language setting is changed.

app/src/main/res/raw/sessions_en.json, app/src/main/res/raw/sessions_ja.json
=> fixed description of ngsw_taro'session

app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleSessionsTabFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsTabFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/StackedPageListener.java, app/src/main/res/drawable/tag_conflict.xml, app/src/main/res/layout/item_session.xml
Just a tiny little bit customize, make it simple and modest expression.
=> Simplify the conflict layout.

app/src/main/java/io/github/droidkaigi/confsched/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched/util/AlarmUtil.java
Fixed bug that notify at once if past session is tapped...
=> fix bug about notification

app/src/main/java/io/github/droidkaigi/confsched/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched/util/LocaleUtil.java
https://github.com/konifar/droidkaigi2016/pull/273/files#r52994581
=> Considered timezone

app/src/main/res/layout/item_session.xml
Removed unnecessary marginTop in session item.
=> Fixed session item layout

app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/MyScheduleFragment.java, app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionsFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Page.java
=> Remove change toolbar colour feature.

app/src/main/res/layout/fragment_about.xml, app/src/main/res/layout/nav_header.xml
=> Delete redundancy code

app/build.gradle
https://github.com/konifar/droidkaigi2016/issues
=> Release 1.1.3

app/src/main/res/raw/sessions_ar.json, app/src/main/res/raw/sessions_en.json, app/src/main/res/raw/sessions_ja.json
Fixed #293
Added available slide_url to jsons.
=> Added slide_urls

app/src/main/res/raw/sessions_ar.json, app/src/main/res/raw/sessions_en.json, app/src/main/res/raw/sessions_ja.json
Add slide_url for No.4 TV向けAndroidアプリの開発TIPSと最新事情 (小林 剛士)
Related: https://github.com/konifar/droidkaigi2016/issues/309
=> Add slide_url for tv_android_tips

README.md, app/src/main/assets/license.html
Added libraries to license and README.
* kvs-scheme
* PermissionDispatchers
=> Add libarary license

app/build.gradle
=> Update permissionsdispatcher version.

circle.yml, gradle.properties
`23.2` was released today.
http://android-developers.blogspot.jp/2016/02/android-support-library-232.html
=> Upgrade support library version

app/src/main/java/io/github/droidkaigi/confsched/MainApplication.java, app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java, app/src/main/java/io/github/droidkaigi/confsched/util/LocaleUtil.java, app/src/main/res/raw/sessions_ko.json, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-ko/strings_urls.xml, app/src/main/res/values/strings.xml
- Added Korean strings.xml
- Added sessions_ko.json
I knew one Korean Androider. His name is [Pluu](https://twitter.com/pluulove). He is translating Japanese session slide of DroidKaigi to Korean.
http://pluu.github.io/tags/#DroidKaigi
I was so impressed. Of course it is not required to support Korean language. But I want to support him. That's the reason.
All Korean text is translated by Google translate. So it is not perfect, but in my opinion, Japanese <=> Korean auto translation is pretty good.
=> Support Korean language

app/src/main/res/raw/sessions_ar.json, app/src/main/res/raw/sessions_en.json, app/src/main/res/raw/sessions_ja.json, app/src/main/res/raw/sessions_ko.json
Corresponding issue: #327
Added movie urls for any sessions which videos are currently available on YouTube.
I thought we have to just wait until videos for all sessions are available, but thought "screw it!"; I just decided to fill out currently available ones and make PR for it if that's possible.
=> Added movie urls for any sessions which videos are currently available on YouTube

app/src/main/res/raw/sessions_ko.json
Support Korean Language
`sessions_ko.json` Translate
=> sessions_ko.json Translate

app/build.gradle, build.gradle
android apk size plugin shows apk size in the end of gradle task.
https://plugins.gradle.org/plugin/com.vanniktech.android.apk.size
```
...
:app:zipalignDevelopDebug
:app:assembleDevelopDebug
Total APK Size in app-develop-debug.apk in bytes: 4801954
```
=> Add gradle apk size plugin

app/build.gradle, app/src/main/java/io/github/droidkaigi/confsched/di/AppModule.java, app/src/main/java/io/github/droidkaigi/confsched/model/Session.java
* Use Orma 2.2.0 to use `renameColumn()`
* Migration: renames `Session.speakerId` to `.speaker`, `.placeId` to `.place`, and `categoryId` to `category`
=> Database Migration

app/src/main/res/values-ar/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/integers.xml, app/src/main/res/values/strings.xml
Removed unused strings and colors and integers.
=> Remove unused resources

app/build.gradle, app/src/main/java/io/github/droidkaigi/confsched/activity/SessionFeedbackActivity.java
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-320
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-200-2016-03-11
https://github.com/gfx/Android-Orma/blob/master/CHANGELOG.md#v232---20160310
=> Update OkHttp, Retrofit, Orma

.gitignore
Fixed .gitignore typo. And add Thumbnail db ignore.
Please confirm :)
=> Fix typo and Add Thumbnail db

app/build.gradle, circle.yml
http://developer.android.com/intl/ja/tools/revisions/build-tools.html
=> Update buildToolsVersion to v23.0.2

app/src/main/java/io/github/droidkaigi/confsched/model/Page.java
=> Refactor Page#forMenuId(MenuItem)

app/build.gradle, build.gradle
I have updated dagger version to use the latest one.
The latest version has a bug fix related to this issue:
http://stackoverflow.com/questions/36378283/project-cannot-be-compiled-after-upgrading-to-gradle2-1-0-alpha5
=> Update dagger 2.0.2->2.2

app/build.gradle, build.gradle
I have updated retrolambda version so that possibly we can reduce 1500-2000 methods and have some other optimization to it.
Reference: 
https://github.com/orfjackal/retrolambda#retrolambda-230-2016-04-30
https://github.com/JakeWharton/retrolambda/blob/605a10acf6aec9449ce5792068dd733dc62ab336/README.md
=> Update retrolambda and use the latest version

app/build.gradle, build.gradle
I have updated versions of RxAndroid and RxJava to get benefit from the latest libraries.
=> Update RxAndroid 1.1.1->1.2.0 and RxJava 1.1.0->1.1.5

app/build.gradle
I have updated retrofit from 2.0.0 to 2.0.2 
https://github.com/square/retrofit#download
=> Update retrofit 2.0.0->2.0.2

app/build.gradle
I have updated OkHttp from 3.2.0 to 3.3.0.
Here is the CHANGELOG: https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-330
=> Update OkHttp 3.2.0 -> 3.3.0

app/build.gradle
Below is the CHANGELOG:
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-331
=> Update OkHttp 3.3.0 -> 3.3.1

app/build.gradle
I have updated stetho to 1.3.1, the latest version. 🙇 
Here is the [CHANGELOG.md](https://github.com/facebook/stetho/blob/master/CHANGELOG.md#version-131)
=> Update stetho 1.3.0->1.3.1

app/src/main/java/io/github/droidkaigi/confsched/activity/VideoPlayerActivity.java, app/src/main/res/layout/activity_video_player.xml
I removed the feature that does not seem to use in VideoPlayerActivity.
If you will use it in future, please close this PR.
=> Simplify VideoPlayerActivity

app/src/main/java/io/github/droidkaigi/confsched/fragment/SessionDetailFragment.java, app/src/main/java/io/github/droidkaigi/confsched/model/Session.java, app/src/main/java/io/github/droidkaigi/confsched/viewmodel/SessionDetailViewModel.java
@konifar said:
> This is not cool.
> I'll change checked status to ObservableField by MVVM way.
I tried using ObservableField.
But ``session = new Session(session);`` is not cool.
I can't to change ``Session`` as immutable object, because this is database depend class.
=> Change fab-changed as ObservableField

app/src/main/java/io/github/droidkaigi/confsched/activity/SearchActivity.java, app/src/main/java/io/github/droidkaigi/confsched/widget/SearchToolbar.java
I think a user will be a little happy. 😄
=> Dismiss keyboard when a user submit keyword

app/build.gradle
https://github.com/ReactiveX/RxJava/blob/1.x/CHANGES.md#version-118---july-23-2016-maven
=> Update RxJava 1.1.7 -> 1.1.8

app/build.gradle
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-341
👯
=> Update OkHttp 3.3.1 -> 3.4.1

app/build.gradle
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-210-2016-06-15
🐢
=> Update retrofit 2.0.2 -> 2.1.0

app/build.gradle
https://github.com/google/gson/blob/master/CHANGELOG.md#version-27
📻
=> Update Gson 2.6.1 -> 2.7

app/build.gradle
=> Update retrofit dependencies to 2.1.0.

app/build.gradle
https://github.com/hotchemi/PermissionsDispatcher/blob/master/CHANGELOG.md#changelog
👼
=> Update PermissionsDispatcher 2.1.2 -> 2.1.3

app/build.gradle
Fix a compilation error at #391
=> Update Dagger 2.2 -> 2.6

app/build.gradle
Yet another update 👼 
Sorry I could not find the library's CHANGELOG. 🙇 
https://github.com/rejasupotaro/kvs-schema
=> Update KVS Schema 5.0.0 -> 5.0.1

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.1.9
=> Update RxJava to 1.1.9.

app/src/androidTest/java/io/github/droidkaigi/confsched/util/LocaleUtilTest.java
=> Simplify test code.

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.1.10
=> Update RxJava to 1.1.10.

build.gradle
- Upgrade Gradle Plugin version from 2.2.0-alpha7 to 2.2.0-rc2
=> Bump up Gradle Plugin version from 2.2.0-alpha7 to 2.2.0-rc2

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.2.0
- Update RxJava version to 1.2.0.
=> Update RxJava version to 1.2.0.

app/build.gradle
I have updated ThreeTenABP library 1.0.3 -> 1.0.4.
The changelog is below:
https://github.com/JakeWharton/ThreeTenABP/blob/master/CHANGELOG.md#version-104-2016-08-27
=> Update ThreeTenABP 1.0.3 -> 1.0.4

app/build.gradle
ref: https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.2.0
=> Update PermissionsDispatcher to 2.2.0.

app/build.gradle
I have updated dagger from 2.6 to 2.7.
Release note: https://github.com/google/dagger/releases/tag/dagger-2.7
=> Update dagger 2.6 -> 2.7

app/build.gradle
I have updated stetho from 1.3.1 to 1.4.1 🍔 
The changelog is below:
https://github.com/facebook/stetho/blob/master/CHANGELOG.md#version-141
=> Update stetho 1.3.1 -> 1.4.1

build.gradle
=> Update Gradle Plugin for Android to 2.2.0

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.2.1
=> Update RxJava to 1.2.1.

app/build.gradle
With lots of bug fixes: https://github.com/gfx/Android-Orma/compare/v3.0.0-rc2...v3.0.0
=> Orma v3.0.0 has been released!

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.2.2
=> Update RxJava to 1.2.2..

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.2.3
=> Update RxJava to 1.2.3.

app/build.gradle
😃 
ref: https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.3.0
- Start Xiaomi support. [#235](https://github.com/hotchemi/PermissionsDispatcher/pull/235).
- Fix slight bug for lint check. [#230](https://github.com/hotchemi/PermissionsDispatcher/pull/230).
=> Update PermissionsDispatcher to 2.3.0.

app/build.gradle
ref: https://github.com/ReactiveX/RxJava/releases/tag/v1.2.4 🖌
=> Update RxJava to 1.2.4.
